# site name
prefixName: 字蘭の 
siteName: 小竹簡
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /img/custom/avatar.png
url: https://blog.byteorchid.com
description: Live your life with passion! With some drive!
cdn: https://cdn.jsdelivr.net/gh/virualv/cdn@1.9
pjax: 1
# 1开启
mathjax: 0

notice: hexo-Sakura主题，Powered by 
lazyloadImg: https://cdn.jsdelivr.net/gh/virualv/cdn@1.9/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/tech/, fa: fa-code }, 
    生活: {path: /categories/life/, fa: fa-file-text-o }, 
    资源: {path: /categories/resource/, fa: fa-cloud-download }, 
    随想: {path: /categories/caprice/, fa: fa-commenting-o },
    转载: {path: /categories/reprint/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    书单: {path: /tags/read/, fa: fa-th-list faa-bounce }, 
    番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
    歌单: {path: /music/, fa: fa-headphones },
    图集: {path: /tags/photo/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    Lab: {path: /lab/, fa: fa-cogs },
  } }
  客户端: { path: /client/, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/virualv/cdn@1.9/img/cover/(1).jpg.webp
  - https://cdn.jsdelivr.net/gh/virualv/cdn@1.9/img/cover/(2).jpg.webp
  - https://cdn.jsdelivr.net/gh/virualv/cdn@1.9/img/cover/(3).jpg.webp
  - https://cdn.jsdelivr.net/gh/virualv/cdn@1.9/img/cover/(4).jpg.webp
  - https://cdn.jsdelivr.net/gh/virualv/cdn@1.9/img/cover/(5).jpg.webp
  - https://cdn.jsdelivr.net/gh/virualv/cdn@1.9/img/cover/(6).jpg.webp

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img`
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png}
  - {url: https://space.bilibili.com/42002642, title: Bilibili, desc: 博主的b站视频, img: /img/startdash/bilibili.jpg}
  - {url: /, title: 字蘭的工具库, desc: 技术服务, img: /img/startdash/wangshiwu.jpg}



# your site build time or founded date
siteBuildingTime: 02/16/2017

#social  url, img PC端配置
social:
  github: {url: https://github.com/virualv, img: /img/social/github.png}
  sina: {url: https://weibo.com/p/1005055646696537, img: /img/social/sina.png}
  wangyiyun: {url: https://music.163.com/#/user/home?id=96254842, img: /img/social/wangyiyun.png}
  zhihu: {url: https://www.zhihu.com/people/virtualv, img: /img/social/zhihu.png}
  email: {url: mailto:virualv@gmail.com, img: /img/social/email.svg}
  wechat: {url: /#, qrcode: /img/custom/wechat.png, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: https://github.com/virualv, fa: fa-github, color: 333}
  weibo: {url: https://weibo.com/p/1005055646696537, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=568239212&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  paypal: https://www.paypal.me/virualv
  alipay: /img/custom/donate/AliPayQR.png
  wechat: /img/custom/donate/WePayQR.png
  wechatSQ: /img/custom/donate/WePaySQR.jpg

# 视频地址为http://go.plvideo.cn/front/video/preview?vid=a0d43a4d360fc84adbe3a21e1b992b8a_a，配置如下
movies:
  url: http://go.plvideo.cn/front/video
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: preview?vid=a0d43a4d360fc84adbe3a21e1b992b8a_a

aplayer: 
  id: 96254842
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: GyC3NzMvd0hT9Yyd2hYIC0MN-gzGzoHsz
v_appKey: mgOpfzbkHYqU92CV4IDlAUHQ

